### PR TITLE
Add showtimes feature.

### PR DESCRIPTION
**Pull request by kostyafarber**
## PR Description
Add a feature that allows users to obtain showtimes for movies at cinemas near them with this page https://www.imdb.com/showtimes/.

Fixes issue https://github.com/cinemagoer/cinemagoer/issues/232.

### CODE REVIEW

**Comment by alberanid** [comment]
Thanks, I'll look at it as soon as possible.

**Comment by alberanid** [comment]
Thanks! That's an excellent starting point.

Few notes, mostly for myself:

* [ ] add a test under "tests"
* [ ] also extract the separator (change the XPath to `./../../..//div[@class="showtimes"]//text()`)
* [ ] the method should not return the `data` object, but only its content
* [ ] rename `get_showtimes` to `_get_showtimes` in subclasses
* [ ] movie titles should be `Movie` instances
* [ ] think of a better data structure; maybe a list of objects [{'cinema': 'Cinema Name', 'movie': MovieInstance, 'show times': 'date / times'}, ...]

I can work on most of them in the next few day (but if you prefer to do it, let me know).

I've just some doubts about the last point, but I gess something like that will be good. If you have other ideas, let me know!

Thanks.

**Comment by kostyafarber** [comment]
Hey! Thanks for the list of tasks. I'm happy for you to work on it in the next couple of days (you'll probably finish it faster than me). If you get busy or something just ping me here and I can pick some of these up.

 I can have a think about the data structure for the showtimes, but I think a list of objects would be better.

Thanks for your help!

**Comment by alberanid** [comment]
Hi @kostyafarber ,

Sure, if you want to work on some of the points in the next days go ahead.

Don't worry if you don't have time or you don't know how to change stuff: do whatever you want and let me know when you are done so that I can take over for the missing parts.

Thanks!

**Comment by kostyafarber** [comment]
No worries @alberanid I'll try work on these and then ping you once I've done what I can! Cheers!

**Comment by kostyafarber** [comment]
Hey! @alberanid I tried to incorporate as much of your checklist as I could.    

> Thanks! That's an excellent starting point.
> 
> Few notes, mostly for myself:
> 
> * [x]  add a test under "tests"
> * [x]  also extract the separator (change the XPath to `./../../..//div[@class="showtimes"]//text()`)
> * [x]  the method should not return the `data` object, but only its content
> * [x]  rename `get_showtimes` to `_get_showtimes` in subclasses
> * [x]  movie titles should be `Movie` instances
> * [x]  think of a better data structure; maybe a list of objects [{'cinema': 'Cinema Name', 'movie': MovieInstance, 'show times': 'date / times'}, ...]
> 
> I can work on most of them in the next few day (but if you prefer to do it, let me know).
> 
> I've just some doubts about the last point, but I gess something like that will be good. If you have other ideas, let me know!
> 
> Thanks.

I changed the data structure a bit to be a list of objects. 

I still kind of think it makes sense to keep the keys as cinema names. As each 'entity' is a cinema in which there are lists of movies for that cinema with showtimes for those movies. It would be more intuitive to search the object this way I think.

However this might not be the best way and if you think there is a better way to represent it please change it!

I added a small test to make sure that we pick up all cinemas in our object (as stated on the webpage).

Let me know how you go with the rest.

Many thanks.

**Comment by alberanid** [comment]
merged, see the comment on #232 for the changes I made (I hope they don't break too much code)

Thanks!

**Comment by kostyafarber** [comment]
Thanks for your help @alberanid!

**Pull request merged**
